runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: PIL
  version: "1.1.7"
- name: MySQLdb
  version: 1.2.5
- name: django
  version: 1.4

builtins:
- remote_api: on

handlers:
- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js

- url: /static/images
  static_dir: static/images

- url: /static/CACHE/css
  static_dir: static/CACHE/css

- url: /static/CACHE/js
  static_dir: static/CACHE/js

- url: /static/test
  static_dir: static/test

- url: .*
  script: wsgi.application

# - url: /_ah/queue/deferred
#   script: djangoappengine.deferred.handler.application
#   login: admin

# - url: /_ah/stats/.*
#   script: djangoappengine.appstats.application

# - url: /media/admin
#   static_dir: django/contrib/admin/media
#   expiration: '0'

# - url: /.*
#   script: djangoappengine.main.application
#   secure: never

inbound_services:
- mail


skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^install/.*
- ^.*\.sqlite3
- ^static/photo/.*
- ^static/js/.*
- ^static/styles/.*
- ^res/.*
- ^lib/.*
- ^\.git/.*

env_variables:
  DJANGO_SETTINGS_MODULE: "settings_gae"
  DJANGO_NO_COMPRESS_OFFLINE: "false"