version: '3.2'

services:
  db:
    build:
      context: db/
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data

volumes:
    db:
